owid/walden

- README.md
- ingests/wb_income_groups.py
- owid/walden/catalog.py
- owid/walden/ingest.py
Couple of usability improvements after our pairing session with @pabloarosado 
1. Improved documentation
2. Use `Dataset` for type hints instead of creating metadata as a dictionary
3. Clarify some metadata fields
I was thinking about creating its own `DatasetMeta` class and inheriting from it in `Dataset`, but I'm not sure whether that would make it more clear or not...
Lastly, is there a reason why don't we implicitly use extension from file name / url?
> enhance(dataset): use Dataset as type hint

- owid/walden/files.py
- tests/test_files.py
Solves https://github.com/owid/etl/issues/86. Version with `NamedTemporaryFile` didn't calculate md5 checksums correctly on @lucasrodes OS for some reason.
> fix(files): do not stream to NamedTempFile because of weird issues

- owid/walden/catalog.py
- tests/test_catalog.py
Move `version` from property to attribute so that we can set it during initialization. This is necessary for our FAO work.
> refactor(dataset): allow specifying version in init

- ingests/faostat.py
- owid/walden/index/faostat/2022-04-26/faostat_rl.json
* Add "rl" dataset code to FAOstat ingest script.
This dataset code was not included in the list `INCLUDED_DATASETS_CODES`, and I suppose it should be included (since it is used later on in `etl` steps).
> Add faostat dataset to index

- owid/walden/index/faostat/2022-05-17/faostat_metadata.json
There was a problem with the faostat_metadata.json file ingested into walden. I have fixed that, and have updated the md5 in the index file.
> fix(faostat): fix faostat metadata index file

- ingests/faostat.py
- owid/walden/index/faostat/2022-05-17/faostat_metadata.json
The ingest script was fetching only some of the available fields from the FAOSTAT API. In particular, we were not fetching the "items" metadata (that contains the descriptions of the items). Given that the API returns different fields for different datasets, for simplicity now the script will fetch all fields (resulting in a json file of <14MB to be ingested, instead of <6MB).
> Fetch all faostat metadata

- owid/walden/index/faostat/2022-05-17/faostat_rl.json
A dataset was missing in Walden index in the latest version of FAOSTAT (because a previous version already existed). But, given that the content of the index json files has changed (for example, now we have "version") it is better to include the index file of this dataset together with all others.
> data(faostat): add missing FAOSTAT dataset index file

- owid/walden/audit.py
- owid/walden/schema.json
- tests/test_catalog.py
[license_url](https://github.com/owid/walden/blob/master/owid/walden/catalog.py#L71) is already optional, but it wasn't reflected in schema.json that is used by test. This should fix failing tests on master.
> fix(schema): make license_url optional

- owid/walden/catalog.py
- owid/walden/owid_cache.py
PR required for https://github.com/owid/etl/pull/219.
(We should consider moving the entire `owid-cache.py` to [datautils](https://github.com/owid/data-utils-py) as the code is being duplicated elsewhere as well. However, we're blocked by the fact that `data-utils-py` has `owid-catalog-py` as a dependency)
> enhance(catalog): add method for deleting dataset from S3

- owid/walden/files.py
There was an issue where a download step would erroneously display the download progress of previous steps:
> fix: don't display progress bars for previous steps

- owid/walden/__init__.py
- owid/walden/catalog.py
Now that we have more than a thousand datasets, instantiating Walden catalog can take a long time (>2s). This becomes a bottleneck for fast-track. Having global `owid.walden.CATALOG` is a convenient way how to avoid this (and we have something similar in `owid-catalog-py` for `RemoteCatalog`). We can refresh the catalog manually with
```
from owid.catalog import CATALOG as WALDEN_CATALOG
WALDEN_CATALOG.refresh()
```
manual refresh is only used in fast-track, cached version is fine everywhere else.
> feature(catalog): add global catalog

- ingests/un_wpp.py
- owid/walden/index/un/2022-07-11/un_wpp.json
Fix zip folder. In the prior version, the zip folder contained unnecessary and redundant files.
> fix: UN WPP

- poetry.lock
- pyproject.toml
Update owid-datautils version, and also exclude .ipynb_checkpoints from isort checks.
> chore: Update datautils version

- owid/walden/audit.py
Check that we always have `owid_data_url`, meaning that we in fact always cache a copy of the remote data.
This is important because 6m or 1y later the data provider often stops hosting the original data in the same place. At that time, we will really want to have kept a copy so that we can rebuild the dataset.
> chore: audit that we always keep a copy of the data

- owid/walden/catalog.py
- owid/walden/files.py
Fix for https://github.com/owid/etl/issues/552
When someone reuploads a dataset in walden, existing cache in `~/.owid/walden` won't get invalidated and we'll assume we have a correct file even though it has a different checksum. This could be troublesome especially for backported datasets.
In calls to `ensure_downloaded()`, check the checksum against the walden record and re-download the file if there's a checksum mismatch.
Save files in cache as `~/.owid/walden/.../short_name.[md5].[ext]`. If md5 gets updated in walden index, it'll force us to download a new file. This is much faster than checking dirtiness at runtime in `WaldenStep`.
After we merge this, everyone could remove their `~/.owid` folder to free up some space. This will also trigger a completely new rebuild of ETL.
We leave …
> fix(catalog): replace file in ensure_downloaded() if checksum does not match

- ingests/wb/2022-10-28/wb_gender.py
- owid/walden/index/wb/2022-10-29/wb_gender.json
Use date as the version in the dataset name instead of the year. Use `Gender Statistics - World Bank (2022-10-29)` instead of `Gender Statistics - World Bank (2022)`.
> enhance(wb_gender): use date in dataset name instead of year

- owid/walden/catalog.py
Minor addition to #115. Now check on whether the dataset has changed compared to latest available version in Walden is done within `catalog.Dataset.upload`  method.
> enhance(catalog): add option to check if ds has changed when uploading

- owid/walden/catalog.py
- Method `Dataset.upload` now returns a boolean value, stating whether the dataset was uploaded to S3 or not.
- New method `Dataset.upload_and_save`, which encapsulates a commonly used logic (see [slack thread](https://owid.slack.com/archives/C0193RW5E2J/p1667300279895209?thread_ts=1667300015.718369&cid=C0193RW5E2J)).
> enhance(catalog): Dataset.upload, Dataset.upload_and_save

- ingests/papers/2022-11-01/riley2005/__main__.py
- ingests/papers/2022-11-01/riley2005/meta.yml
- owid/walden/index/papers/2022-11-01/papers_riley2005.json
- Add life expectancy at 0 years old from [Estimates of Regional and Global Life Expectancy, 1800-2001 - Riley (2005)](https://u.demog.berkeley.edu/~jrw/Biblio/Eprints/%20P-S/riley.2005_estimates.global.e0.pdf)
- I created a new namespace, `papers`, where we can add the ingest scripts for data coming from specific papers/journals. Same approach as in #117.
This script ingests a PDF. My idea is to parse it somehow later in Meadow. Data is contained in a single small table (see table 1 in link above), so perhaps it is doable.
> data(life-exp): add data from riley2005

- owid/walden/audit.py
Ignore private datasets in audit, otherwise it fails.
> fix: Ignore private datasets in audit

- ingests/ihme/2020-12-19/ihme_child_mortality.py
- ingests/ihme_gbd.py
- ingests/un/2019/un_igme.py
- poetry.lock
- pyproject.toml
In order to reduce and simply dependencies for Python 3.11 support, remove dependency on `owid-catalog-py` for `walden`, and replace it with the new `owid-repack-py` package.
This removes all dependency on `pyarrow`, which is the package that's been blocking the Python 3.11 upgrade.
> enhance: swap owid-catalog-py dep for owid-repack-py
