README.md
index/wpp/2019/wpp_demographic.json

- Added dev environment installation guide
- Added code blocks for shell commands
- Moved wpp_demographic example file to `index/wpp/2019` folder, to be consistent with OWID cache URL.
- Renamed namespace of wpp_demographicto be consistent with OWID cache URL.

README docs improvements and index folder structure fix

---

index/faostat/2021-03-18/faostat_QCL.json
index/faostat/2021-08-18/faostat_FS.json
ingests/faostat.py
owid/walden/catalog.py

Additional minor library enhancements

fao: data update

---

ingests/cait_ghg_emissions.py
owid/walden/index/cait/2022-02-24/cait_ghg_emissions.json
poetry.lock
pyproject.toml

* Add ingest script to fetch data from API and upload it to S3.
* Add metadata for this dataset to index.

Add cait ingest and index

---

ingests/ggdc_maddison.meta.yml
owid/walden/catalog.py
owid/walden/files.py

Main PR https://github.com/owid/etl/pull/133

feature(backport): backport grapher variable to walden

---

owid/walden/files.py
poetry.lock
pyproject.toml
tests/test_files.py

Implements https://github.com/owid/etl/issues/154

feature: Show progress bar for large file downloads

---

ingests/un_sdg.meta.yml
ingests/un_sdg.py
poetry.lock
pyproject.toml

This downloads the data for all 17 Sustainable Development Goals and for all geographic areas.

Ingest script for UN SDG dataset

---

ingests/faostat.py

Add some documentation to the FAOSTAT ingestion script, and let it run in "read-only" mode (to check if there are any updates, without writing to S3 or walden index).

Enhance faostat ingestion

---

ingests/un_wpp.meta.yml

Change dataset name, use `NAME - SOURCE (YEAR)`

enhance: change dataset name

---

poetry.lock
pyproject.toml

Update owid-datautils and owid-catalog versions.

Update owid-datautils and owid-catalog versions

---

poetry.lock
pyproject.toml

chore: Update datautils

---

owid/walden/files.py

Fixes https://github.com/owid/etl/issues/420
Download to `{filename}.tmp`, then move from `{filename}.tmp` to `{filename}` once the download is successful. A failure will leave a `.tmp` file behind, but will not impact correctness.

fix: partial walden download on failure

---

owid/walden/index/smil/2017-01-01/global_primary_energy.json

Traditional biomass was actually given until 2015, so I included it in the dataset.

fix(smil): Add missing Smil data

---

ingests/gcp/2022-09-29/global_carbon_budget.py
ingests/gcp/2022-09-29/global_carbon_budget_global_full.meta.yml
ingests/gcp/2022-09-29/global_carbon_budget_national_flat.meta.yml
ingests/gcp/2022-09-29/global_carbon_budget_national_flat_metadata.meta.yml
ingests/gcp/2022-09-29/global_carbon_budget_national_full.meta.yml
owid/walden/index/gcp/2022-09-29/global_carbon_budget_global_full.json
owid/walden/index/gcp/2022-09-29/global_carbon_budget_national_flat.json
owid/walden/index/gcp/2022-09-29/global_carbon_budget_national_flat_metadata.json
owid/walden/index/gcp/2022-09-29/global_carbon_budget_national_full.json

Add ingest scripts and walden index files for Global Carbon Project's Global Carbon Budget raw data files.

Add global carbon budget data

---

ingests/who_ghe.py
owid/walden/index/who/2022-09-30/ghe.json

Previously data for 2018/19 wasn't included - I think the the query was too big for the API so they got cut off. Now doing a request per cause per year.

Fix to Global Health Estimates

---

ingests/irena/renewable_power_generation_costs.meta.yml
ingests/irena/renewable_power_generation_costs.py
owid/walden/index/irena/2022-10-07/renewable_power_generation_costs.json

Ingest IRENA's Renewable Power Generation Costs data.

Ingest irena data

---

ingests/rff/shared.py
ingests/rff/world_carbon_pricing__subnational.meta.yml
ingests/rff/world_carbon_pricing__subnational.py
owid/walden/index/rff/2022-09-14/world_carbon_pricing__subnational.json

Add sub-national carbon pricing data.

Add subnational carbon pricing data

---

poetry.lock
pyproject.toml

Update datautils version to v0.5.0-alpha.

chore: datautils v0.5.0-alpha

---

ingests/irena/2022-10-25/renewable_energy_patents.meta.yml
ingests/irena/2022-10-25/renewable_energy_patents.py
owid/walden/index/irena/2022-10-25/renewable_energy_patents.json

* Create ingest script to manually upload file to Walden (since the data is hard to fetch in any programmatic way).
* Add Walden index file.

Get irena patents data

---

owid/walden/catalog.py

Check if a Walden dataset differs from its latest version in Walden. This can be useful when trying to update a Walden dataset.
Comparison is done based on md5 hash.

feat(dataset): check if dataset needs update

---

.mypy.ini
Makefile
owid/walden/catalog.py
owid/walden/files.py
owid/walden/ingest.py
poetry.lock
pyproject.toml

Replace mypy by pyright. (Had to explicitly add `pyrsistent` to dependencies to fix failing build)

enhance(tools): replace mypy by pyright

---

ingests/wb/2022-10-28/wb_gender.meta.yml
owid/walden/index/wb/2022-10-29/wb_gender.json

Changing source name to `World Bank, Gender Statistics (based on multiple sources)` after discussion in https://github.com/owid/owid-issues/issues/229

enhance(wbgender): source name
